### ISSUE TITLE
python_bytes_to_unicode fail with unknown encoding

### ISSUE THREAD

**Issue by muffinmad** [davidhalter/parso#107]
```
$ mkdir test-bad-coding && cd test-bad-coding
$ echo "# coding: wtf-12" > bad-coding.py
```

```python
Python 3.7.4 (default, Sep 28 2019, 16:39:19)
>>> from jedi import Script
>>> script = Script('foo', path='foo.py')
>>> script.get_references()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/helpers.py", line 482, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/__init__.py", line 525, in get_references
    return _references(**kwargs)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/__init__.py", line 519, in _references
    names = find_references(self._get_module_context(), tree_name)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 143, in find_references
    for module_context in potential_modules:
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 269, in get_module_contexts_containing_name
    limit_reduction=limit_reduction):
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 281, in search_in_file_ios
    m = _check_fs(inference_state, file_io, regex)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 168, in _check_fs
    code = python_bytes_to_unicode(code, errors='replace')
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/parso/utils.py", line 109, in python_bytes_to_unicode
    return unicode(source, encoding, errors)
LookupError: unknown encoding: wtf-12
```

I'm faced this issue with simpler STR:

```python
>>> from jedi import Script
>>> Script('from inspect import Parameter').get_references(1, 29)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/helpers.py", line 482, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/__init__.py", line 525, in get_references
    return _references(**kwargs)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/api/__init__.py", line 519, in _references
    names = find_references(self._get_module_context(), tree_name)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 143, in find_references
    for module_context in potential_modules:
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 269, in get_module_contexts_containing_name
    limit_reduction=limit_reduction):
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 281, in search_in_file_ios
    m = _check_fs(inference_state, file_io, regex)
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/jedi/inference/references.py", line 168, in _check_fs
    code = python_bytes_to_unicode(code, errors='replace')
  File "/Users/mad/Library/Python/3.7/lib/python/site-packages/parso/utils.py", line 109, in python_bytes_to_unicode
    return unicode(source, encoding, errors)
LookupError: unknown encoding: uft-8
```

because of the file on my machine `/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/bad_coding.py` with this content:

```python
# -*- coding: uft-8 -*-
```

**Comment by davidhalter** [comment]
@muffinmad You really seem to uncover all the weird cases :)

In general, are you comfortable/interested to fix issues yourself? You write great test cases, so you might as well be able to fix those issues :) I'm generally happy to assist!

**Comment by muffinmad** [comment]
> @muffinmad You really seem to uncover all the weird cases :)

By coincidence, I haven't experience such weird cases for years of use plugins based on your awesome library for almost every editor, until I made my own LSP server :)

> In general, are you comfortable/interested to fix issues yourself? You write great test cases, so you might as well be able to fix those issues :) I'm generally happy to assist!

Deal! From now on I'll try to create PR before issues. :)

Thanks!
