### ISSUE TITLE
Index error when parsing parameters with wrong bare asterisk usage

### ISSUE THREAD

**Issue by micbou** [davidhalter/parso#44]
The following code (the `version` parameter can be any Python 3):
```python
import parso
parso.parse('def test(arg, *):\n    pass', version='3.6')
```
raises an `IndexError` exception:
```sh
Traceback (most recent call last):
  File "parso\parser.py", line 178, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(ENDMARKER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 9, in <module>
    parso.parse('def test(arg, *):\n    pass', version='3.6')
  File "parso\__init__.py", line 58, in parse
    return grammar.parse(code, **kwargs)
  File "parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "parso\grammar.py", line 141, in _parse
    root_node = p.parse(tokens=tokens)
  File "parso\python\parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "parso\parser.py", line 128, in parse
    self._add_token(token)
  File "parso\parser.py", line 182, in _add_token
    self._pop()
  File "parso\parser.py", line 206, in _pop
    new_node = self.convert_node(tos.dfa.from_rule, tos.nodes)
  File "parso\python\parser.py", line 93, in convert_node
    return self.node_map[nonterminal](children)
  File "parso\python\tree.py", line 570, in __init__
    parameters.children[1:-1] = _create_params(parameters, parameters.children[1:-1])
  File "parso\python\tree.py", line 540, in _create_params
    if param_children[0] == '*' and param_children[1] == ',' \
IndexError: list index out of range
```
This occurs on Parso e05d7fd59f301296dea705173de70d60a4a5d9e9.

**Comment by davidhalter** [comment]
Thanks for finding this!
