### ISSUE TITLE
AssertionError thrown on autocomplete keyword `from`

### ISSUE THREAD

**Issue by sw00** [davidhalter/parso#56]
Running from a `pipenv` managed virtualenv (Python 3.6.5).

I'm using Neovim v0.3.1 with `deoplete-jedi`. Trying to autocomplete after typing any keyword throws this exception:

```
[deoplete] Traceback (most recent call last):
  File "/home/sett/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 179, in _gather_results
    result = self._get_result(context, source)
  File "/home/sett/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 234, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 167, in gather_candidates
    environment=self._env)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 119, in get_script
    return jedi.Script(source, line, col, filename, environment=self._env)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 118, in __init__
    cache_path=settings.cache_directory,
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/__init__.py", line 388, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/grammar.py", line 126, in _parse
    new_lines=lines
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 236, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 289, in _copy_from_old_parser
    line_offset
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 598, in copy_nodes
    self.prefix,
  File "/home/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 686, in _copy_nodes
    assert last_line_offset_leaf == ':'
AssertionError
Error from jedi: AssertionError().  Use :messages / see above for error details.
```

Simply removing/commenting offending line (line 686, diff.py) makes it work normally.

**Comment by blueyed** [comment]
What is `last_line_offset_leaf` in that case?
Are you using the latest parso (v0.3.2) with deoplete-jedi?  (it was updated there recently)

Completion of `whi` works for me with deoplete-jedi.
Can you provide steps to reproduce this easily, e.g. by only using jedi/parso?

**Comment by sw00** [comment]
I've manually checked out both vendored Parso and Jedi to their respective `origin/master`s.
Parso is at revision `076e29649765a30eb993102697fcdd0fb92228fb`.
Jedi is at revisision `9617d4527de583b0b900166e4430a8964ee67dc6`.

Applying the following patch to get more details in logging.
```
diff --git a/parso/python/diff.py b/parso/python/diff.py
index 6c119e5..841d534 100644
--- a/parso/python/diff.py
+++ b/parso/python/diff.py
@@ -683,7 +683,9 @@ class _NodesTree(object):
                 if last.type == 'decorated':
                     last = last.children[-1]
                 last_line_offset_leaf = last.children[-2].get_last_leaf()
-                assert last_line_offset_leaf == ':'
+                if not last_line_offset_leaf == ':':
+                    raise AssertionError(str(last_line_offset_leaf))
+
             else:
                 last_line_offset_leaf = new_nodes[-1].get_last_leaf()
             tos.add_tree_nodes(prefix, new_nodes, line_offset, last_line_offset_leaf)
```

Reveals this traceback:
```
  File "/Users/sett/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 687, in _copy_nodes
    raise AssertionError(str(last_line_offset_leaf))
AssertionError: <Keyword: async>
Error from jedi: AssertionError(<Keyword: async>,).  Use :messages / see above for error details.
[deoplete] Too many errors from "jedi". This source is disabled until Neovim is restarted.
```

I'm launching neovim from a Python 3.6.5 virtualenv with the following `pip freeze` output:
```
aioconsole==0.1.8
aiodns==1.1.1
aiohttp==2.3.10
aiohttp-cors==0.7.0
aiohttp-swagger==1.0.5
aiokatcp==0.3.1
aiomonitor==0.3.0
alabaster==0.7.10
arrow==0.12.1
async-generator==1.9
async-timeout==2.0.1
asyncio-nats-client==0.8.2
asyncpg==0.16.0
asynctest==0.11.1
atomicwrites==1.2.1
attrs==18.2.0
Babel==2.6.0
blosc==1.5.1
cbor==1.0.0
cchardet==2.1.1
certifi==2018.11.29
chardet==3.0.4
coverage==4.5.1
decorator==4.3.0
docutils==0.14
idna==2.6
idna-ssl==1.0.1
imagesize==1.0.0
Jinja2==2.10
katstore==0.1.dev752+user.johan.mt.181.katstore.sync.e054e5b.dirty
katversion==0.8
MarkupSafe==1.0
more-itertools==5.0.0
multidict==4.3.1
numexpr==2.6.5
numpy==1.14.3
omnijson==0.1.2
packaging==19.0
pluggy==0.8.1
pockets==0.6.2
psutil==5.4.5
py==1.5.3
pycares==2.3.0
Pygments==2.2.0
pyparsing==2.2.0
pytest==3.2.5
pytest-aiohttp==0.3.0
pytest-asyncio==0.8.0
pytest-capturelog==0.7
pytest-cov==2.5.1
pytest-mock==1.10.0
pytest-timeout==1.2.1
python-dateutil==2.7.3
pytz==2018.4
PyYAML==4.2b4
requests==2.20.0
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.7.5
sphinx-autodoc-typehints==1.3.0
sphinxcontrib-asyncio==0.2.0
sphinxcontrib-napoleon==0.6.1
sphinxcontrib-websupport==1.1.0
ssh-import-id==5.0
tables==3.4.3
terminaltables==3.1.0
typing==3.6.6
ujson==1.35
urllib3==1.23
yarl==1.2.0
```

**Comment by blueyed** [comment]
Thanks for the info already.

Can you elaborate on the following please, i.e. provide steps to reproduce it:

> Trying to autocomplete after typing any keyword

I have deoplete-jedi, so could also test it then.

Maybe some of your installed packages is not compatible with Python 3.6, i.e. it uses "async" as a variable, and parso fails to handle it then.

**Comment by TakaakiFuruse** [comment]
I had the same error.
My editor is spacemacs, python is 3.7.2 and parso is v0.3.2.

When I just typed the ) of  Hello") and pressed enter, I had the same error.

```
import time
import asyncio


async def main():
    print(f"{time.ctime()}, Hello")
```

Also I applied @sw00 's patch and here's the output.

```
  File "/home/orz/.pyenv/versions/3.7.2/lib/python3.7/site-packages/parso/python/diff.py", line 688, in _copy_nodes
    raise AssertionError(str(last_line_offset_leaf))
AssertionError: <Keyword: async>
```

**Comment by kef95** [comment]
I can reproduce both errors posted by @sw00 
The first one makes editing a file practically impossible, and eventually Jedi gets disabled because of too many errors
Running python 3.6.7 on Ubuntu 18.04.1 LTS

**Comment by davidhalter** [comment]
As a temporary workaround you can disable diff parsing in Jedi's settings. I will try to find a solution in the meantime.

**Comment by kef95** [comment]
Sorry but how exactly do you disable it?

**Comment by davidhalter** [comment]
I don't seem to be able to reproduce it. If it's possible for anyone, it would be really nice to write down reproduction steps that I can just run (with `jedi.Script().completions` or parso calls). Otherwise a good description of what you're doing would also do the job.

@kef95 `jedi.settings.fast_parser = False`

**Comment by davidhalter** [comment]
Ok, I figured it out. Thanks for the report. I will be doing a release today.

It's a bit unfortunate that I didn't really have async code around for fuzzing. After I created some, the fuzzer found it in like 0.5 seconds. Now it has been running for an hour and everything is still working.

Well, this is a bit unfortunate. I hope it won't happen again.

**Comment by davidhalter** [comment]
Parso 0.3.3 is out.

**Comment by kef95** [comment]
Thank you for the update. Good work on the fix!

**Comment by TakaakiFuruse** [comment]
Thanks for the update. It's working now!!
