### ISSUE TITLE
AttributeError: 'PythonNode' object has no attribute 'string_prefix'

### ISSUE THREAD

**Issue by awwong1** [davidhalter/parso#57]
Using `Python 3.6.7` and Parso `0.3.2`

```python
from parso import load_grammar

grammar = load_grammar()
module = grammar.parse('%p25%=" & echoc -y "F" & echoc -w "')
errors = grammar.iter_errors(module)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/grammar.py", line 165, in iter_errors
    return self._get_normalizer_issues(node, self._error_normalizer_config)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/grammar.py", line 185, in _get_normalizer_issues
    normalizer.walk(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 34, in walk
    value = self.visit(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 280, in visit
    return super(ErrorFinder, self).visit(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 45, in visit
    return ''.join(self.visit(child) for child in children)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 45, in <genexpr>
    return ''.join(self.visit(child) for child in children)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 280, in visit
    return super(ErrorFinder, self).visit(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 45, in visit
    return ''.join(self.visit(child) for child in children)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 45, in <genexpr>
    return ''.join(self.visit(child) for child in children)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 280, in visit
    return super(ErrorFinder, self).visit(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 44, in visit
    with self.visit_node(node):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 285, in visit_node
    self._check_type_rules(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 54, in _check_type_rules
    rule.feed_node(node)
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/normalizer.py", line 182, in feed_node
    if self.is_issue(node):
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 580, in is_issue
    if first_is_bytes != self._is_bytes_literal(string):
  File "/home/alexander/sandbox/src/git.udia.ca/alex/msr-2019-analysis/venv/lib/python3.7/site-packages/parso/python/errors.py", line 573, in _is_bytes_literal
    return 'b' in string.string_prefix.lower()
AttributeError: 'PythonNode' object has no attribute 'string_prefix'
```

Is this expected? I'm doing some data mining and my input source code is not guaranteed to be python source code.

**Comment by davidhalter** [comment]
This is definitely not expected. I think f-string support made me not realize this was an issue.

**Comment by davidhalter** [comment]
0.3.3 has been released. Please upgrade.
