### ISSUE TITLE
Python 3.7.2 and diff parser

### ISSUE THREAD

**Issue by iced** [davidhalter/parso#58]
Issue is consistently reproducible with python 3.7.2 and doesn't exist with python 3.5.6.

I'm using parso (used from anaconda-mode/jedi, but that should not matter - I'm pretty sure it's easy to reproduce with 2 direct parso invokes, but sadly I don't have time for this right now) and encountering following error time to time:

```
Traceback (most recent call last):
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/service_factory-0.1.5-py3.7.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 97, in wrapper
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/jedi-0.13.2-py3.7.egg/jedi/api/__init__.py", line 118, in __init__
    cache_path=settings.cache_directory,
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/jedi-0.13.2-py3.7.egg/jedi/evaluate/__init__.py", line 388, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/grammar.py", line 126, in _parse
    new_lines=lines
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/python/diff.py", line 236, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/python/diff.py", line 289, in _copy_from_old_parser
    line_offset
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/python/diff.py", line 598, in copy_nodes
    self.prefix,
  File "/root/.emacs.d/var/anaconda-mode/0.1.13/parso-0.3.2-py3.7.egg/parso/python/diff.py", line 686, in _copy_nodes
    assert last_line_offset_leaf == ':'
AssertionError
```

Apparently it got something to do with parser results caching/diffing. After some code reading/debugging of diff.py I decided to turn it off in jedi (jedi.settings.fast_parser = False) and problem disappeared for 3.7.2 as well.

I don't think it's high priority issue but it'd be nice if it'll be fixed at some point.

**Comment by davidhalter** [comment]
Closing in favor of #56. Seems to be the same issue.

**Comment by davidhalter** [comment]
0.3.3 has been released!

**Comment by iced** [comment]
But why it worked with python-3.5?

**Comment by davidhalter** [comment]
To be honest with you, I have no idea. I was able to trigger the bug in 3.5 as well.

**Comment by iced** [comment]
Anyway, all works now, thanks, you are real lifesaver.
