### ISSUE TITLE
Parsing f-strings with nested format specifiers produces incorrect SyntaxError

### ISSUE THREAD

**Issue by gousaiyang** [davidhalter/parso#74]
Hello! I think I've found an issue with parsing f-strings with nested format specifiers (this should be a very rare use case though).

```python
import parso
x = 1
y = 2
test_fmtspec_in_fmtspec = """f'{x:{y:1}}'"""
print(f'Result: {eval(test_fmtspec_in_fmtspec)!r}')
module = parso.parse(test_fmtspec_in_fmtspec, error_recovery=False)
```

The code `test_fmtspec_in_fmtspec` is syntactically valid according to [Python document of f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings):

```
Top-level format specifiers may include nested replacement fields. These nested fields may include their own conversion fields and format specifiers, but may not include more deeply-nested replacement fields. The format specifier mini-language is the same as that used by the string .format() method.
```

But the code above will produce an exception:

```
Result: ' 1'
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\parso\parser.py", line 181, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(NUMBER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_fmtspec_in_fmtspec.py", line 6, in <module>
    module = parso.parse(test_fmtspec_in_fmtspec, error_recovery=False)
  File "C:\Python37\lib\site-packages\parso\__init__.py", line 58, in parse
    return grammar.parse(code, **kwargs)
  File "C:\Python37\lib\site-packages\parso\grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "C:\Python37\lib\site-packages\parso\grammar.py", line 146, in _parse
    root_node = p.parse(tokens=tokens)
  File "C:\Python37\lib\site-packages\parso\python\parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "C:\Python37\lib\site-packages\parso\parser.py", line 128, in parse
    self._add_token(token)
  File "C:\Python37\lib\site-packages\parso\parser.py", line 187, in _add_token
    self.error_recovery(token)
  File "C:\Python37\lib\site-packages\parso\python\parser.py", line 151, in error_recovery
    return super(Parser, self).error_recovery(token)
  File "C:\Python37\lib\site-packages\parso\parser.py", line 151, in error_recovery
    raise ParserSyntaxError('SyntaxError: invalid syntax', error_leaf)
parso.parser.ParserSyntaxError: ('SyntaxError: invalid syntax', <ErrorLeaf: TokenType(NUMBER):'1', (1, 8)>)
```

I tested the code on both Python 3.7 and Python 3.6, both will produce this exception.
(I'm using parso 0.4.0)

**Comment by davidhalter** [comment]
Thanks for finding this!
