### ISSUE TITLE
Parsing f-strings with invalid quotes in expression part does not raise SyntaxError

### ISSUE THREAD

**Issue by gousaiyang** [davidhalter/parso#86]
Hello! I think I've found a small issue with parsing f-strings with invalid quotes in the expression part.

```
>>> import parso
>>> parso.parse("f'{ ''}'", error_recovery=False)
<Module: @1-1>
```

The code being parsed above is syntactically invalid, but parso is not generating an error.  
However, I found that when I remove the leading the space in the expression part (before the invalid quote), parso works correctly.

```
>>> import parso
>>> parso.parse("f'{''}'", error_recovery=False)
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\parso\parser.py", line 181, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(FSTRING_END)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\parso\__init__.py", line 58, in parse
    return grammar.parse(code, **kwargs)
  File "C:\Python38\lib\site-packages\parso\grammar.py", line 78, in parse
    return self._parse(code=code, **kwargs)
  File "C:\Python38\lib\site-packages\parso\grammar.py", line 147, in _parse
    root_node = p.parse(tokens=tokens)
  File "C:\Python38\lib\site-packages\parso\python\parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "C:\Python38\lib\site-packages\parso\parser.py", line 128, in parse
    self._add_token(token)
  File "C:\Python38\lib\site-packages\parso\parser.py", line 187, in _add_token
    self.error_recovery(token)
  File "C:\Python38\lib\site-packages\parso\python\parser.py", line 151, in error_recovery
    return super(Parser, self).error_recovery(token)
  File "C:\Python38\lib\site-packages\parso\parser.py", line 151, in error_recovery
    raise ParserSyntaxError('SyntaxError: invalid syntax', error_leaf)
parso.parser.ParserSyntaxError: ('SyntaxError: invalid syntax', <ErrorLeaf: TokenType(FSTRING_END):"'", (1, 3)>)
```

Maybe there is a subtle bug when parsing the expression part? As for my test, this bug happens on both Python 3.8 and Python 3.6.
(I'm using parso 0.5.1)

**Comment by davidhalter** [comment]
Thanks, it looks like it's a bug, because there are no errors raised either. What you're doing it not enough to get all errors. You will have to use `iter_errors`. However since `iter_errors` also doesn't find anything, it really looks like it's a bug.

```
>>> grammar = parso.load_grammar()
>>> grammar.parse("f'{ ''}'")
<Module: @1-1>
>>> module = grammar.parse("f'{ ''}'")
>>> grammar.iter_errors(module)
[]
```
